# Site settings
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://bketen.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Burak Keten'
  email: brk_ktn_16@hotmail.com
  twitter_username: brk_ktn
  facebook_username: -
  github_username:  bketen
  linkedin_username:  -

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
