# Site settings
title: Burak Keten
description: '#engineer #robotics #stm8'
url: 'http://burakketen.com'
baseurl: '/'
google_verification: 4ANJ6Vx0S3vacJtU2Dhz-uJXBOoV4DqlpcKW6Bwfhio
google_analytics: 'UA-119742857-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Burak Keten'
  email: mail.burakketen@gmail.com
  twitter_username: brk_ktn
  facebook_username: burak.keten.1
  #github_username:  bketen
  #dribbble_username:  bketen
  #behance_username:  bketen
  linkedin_username: bketen

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
